# Config to define all available selections
# Selections contain object- and event-level cuts
# Previously defined selections can be imported with '<<' or '*'
# Any nested collections created by "<<" or '*' operations will be flattened in sidm_processor.py


# Cuts to apply to objects that are clustered into lepton jets
ljsource_cuts: &ljsource_cuts
  obj_cuts: &obj_ljsource_cuts
    electrons: 
      - "pT > 10 GeV"
      - "|eta| < 2.4"
      - "looseID"
    muons: 
      - "looseID"
      - "pT > 5 GeV"
      - "|eta| < 2.4"
    photons:
      - "pT > 20 GeV"
      - "|eta| < 2.5"
      - "looseID"
    dsaMuons: 
      - "pT > 10 GeV"
      - "|eta| < 2.4"
      - "ifcsczero"
      - "segOverlap < 0.66"
      - "extrapolatedDr > 0.2" 
      - "isSubsetAnyPFMuon False"
      - "normChi2 < 4"
      - "DT + CSC hits > 12"
      - "DT + CSC stations >= 2"
      - "ptErrorOverPT < 1"

# PV filter and cosmic veto
pvAndCosmic_cuts: &pvAndCosmic_cuts
  obj_cuts: &obj_pvAndCosmic_cuts
    pvs: 
      - "ndof > 4"
      - "|z| < 24 cm"
      - "|rho| < 0.2 mm"
  evt_cuts: &evt_pvAndCosmic_cuts
    - "PV filter"
    - "Cosmic veto"

baseNoLj: &baseNoLj
  <<: *pvAndCosmic_cuts
  obj_cuts: &obj_baseNoLj
    <<: *obj_ljsource_cuts
    <<: *obj_pvAndCosmic_cuts
  evt_cuts: &evt_baseNoLj
    - *evt_pvAndCosmic_cuts

base: &base
  obj_cuts: &obj_base
    <<: *obj_baseNoLj
  lj_cuts: &lj_base
    - "pT > 30 GeV"
    - "|eta| < 2.4"
  evt_cuts: &evt_base
    - *evt_baseNoLj
    - ">=2 LJs"
    
4mu: &4mu
  <<: *base
  evt_cuts: &evt_4mu
    - *evt_base
    - "4mu"

2mu2e: &2mu2e
  <<: *base
  evt_cuts: &evt_2mu2e
    - *evt_base
    - "2mu2e"

# basic analysis selections with LJ-A dR matching
matchedLj: &matchedLj
  obj_cuts: &obj_matchedLj
    <<: *obj_base
  lj_cuts: 
    - *lj_base
    - "dR(LJ, A) < 0.2"
  evt_cuts: &evt_matchedLj
    - *evt_base
    - ">=2 matched As"

4mu_matchedLj: &4mu_matchedLj
  <<: *matchedLj
  evt_cuts: &evt_4mu_matchedLj
    - *evt_matchedLj
    - "4mu"

2mu2e_matchedLj: &2mu2e_matchedLj
  <<: *matchedLj
  evt_cuts: &evt_2mu2e_matchedLj
    - *evt_matchedLj
    - "2mu2e"

# basic selections with cuts on A properties and no LJ cuts
baseNoLj_promptA: &baseNoLj_promptA
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    genAs:
      - "lxy < 10 cm"

baseNoLj_displacedA: &baseNoLj_displacedA
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    genAs:
      - "10 cm <= lxy < 100 cm"

baseNoLj_veryDisplacedA: &baseNoLj_veryDisplacedA
  <<: *baseNoLj
  obj_cuts:
    <<: *obj_baseNoLj
    genAs:
      - "lxy >= 100 cm"

# Selections for electrons only
# All reco electrons in the barrel
barrelE: &barrelE
  evt_cuts:
    - "Keep all evts"
  obj_cuts: &obj_barrelE
    electrons: &e_barrelE
      - "|eta| < 1.479"

# same as above, but with electron-genA dR matching
barrelE_matched: &barrelE_matched
  <<: *barrelE
  obj_cuts:
    <<: *obj_barrelE
    electrons:
      - *e_barrelE
      - "dR(e, A) < 0.5"

# All reco electrons in the endcaps
endcapE: &endcapE
  evt_cuts:
    - "Keep all evts"
  obj_cuts: &obj_endcapE
    electrons: &e_endcapE
      - "1.479 < |eta| < 2.4"

# same as above, but with electron-genA dR matching
endcapE_matched: &endcapE_matched
  <<: *endcapE
  obj_cuts:
    <<: *obj_endcapE
    electrons:
      - *e_endcapE
      - "dR(e, A) < 0.5"

# Loose reco electrons in the barrel
looseBarrelE: &looseBarrelE
  evt_cuts:
    - "Keep all evts"
  obj_cuts: &obj_looseBarrelE
    <<: *obj_barrelE
    electrons: &e_looseBarrelE
      - *e_barrelE
      - "pT > 10 GeV"
      - "looseID"

# same as above, but with electron-genA dR matching
looseBarrelE_matched: &looseBarrelE_matched
  <<: *looseBarrelE
  obj_cuts:
    <<: *obj_looseBarrelE
    electrons:
      - *e_looseBarrelE
      - "dR(e, A) < 0.5"

# Loose reco electrons in the endcaps
looseEndcapE: &looseEndcapE
  evt_cuts:
    - "Keep all evts"
  obj_cuts: &obj_looseEndcapE
    <<: *obj_endcapE
    electrons: &e_looseEndcapE
      - *e_endcapE
      - "pT > 10 GeV"
      - "looseID"

# same as above, but with electron-genA dR matching
looseEndcapE_matched: &looseEndcapE_matched
  <<: *looseEndcapE
  obj_cuts:
    <<: *obj_looseEndcapE
    electrons:
      - *e_looseEndcapE
      - "dR(e, A) < 0.5"

# N-1 selections
barrelE_ID-sigmaIetaIeta: &barrelE_ID-sigmaIetaIeta
  <<: *barrelE
  obj_cuts: &obj_barrelE_ID-sigmaIetaIeta
    <<: *obj_barrelE
    electrons: &e_barrelE_ID-sigmaIetaIeta
      - *e_barrelE
      - "barrel DPhiInCut"
      - "barrel DEtaInSeedCut"
      - "barrel InverseCut"
      - "barrel Iso"
      - "barrel ConversionVeto"
      - "barrel H/E"
      - "barrel MissingHits"

# same as above, but with electron-genA dR matching
barrelE_ID-sigmaIetaIeta_matched: &barrelE_ID-sigmaIetaIeta_matched
  <<: *barrelE_ID-sigmaIetaIeta
  obj_cuts:
    <<: *obj_barrelE_ID-sigmaIetaIeta
    electrons:
      - *e_barrelE_ID-sigmaIetaIeta
      - "dR(e, A) < 0.5"

barrelE_ID-DPhiIn: &barrelE_ID-DPhiIn
  <<: *barrelE
  obj_cuts: &obj_barrelE_ID-DPhiIn 
    <<: *obj_barrelE
    electrons: &e_barrelE_ID-DPhiIn
      - *e_barrelE
      - "barrel SigmaIEtaIEtaCut"
      - "barrel DEtaInSeedCut"
      - "barrel InverseCut"
      - "barrel Iso"
      - "barrel ConversionVeto"
      - "barrel H/E"
      - "barrel MissingHits"

# same as above, but with electron-genA dR matching
barrelE_ID-DPhiIn_matched: &barrelE_ID-DPhiIn_matched
  <<: *barrelE_ID-DPhiIn
  obj_cuts:
    <<: *obj_barrelE_ID-DPhiIn
    electrons:
      - *e_barrelE_ID-DPhiIn
      - "dR(e, A) < 0.5"

barrelE_ID-EtaInSeed: &barrelE_ID-EtaInSeed
  <<: *barrelE
  obj_cuts: &obj_barrelE_ID-EtaInSeed
    <<: *obj_barrelE
    electrons: &e_barrelE_ID-EtaInSeed
      - *e_barrelE
      - "barrel SigmaIEtaIEtaCut"
      - "barrel DPhiInCut"
      - "barrel InverseCut"
      - "barrel Iso"
      - "barrel ConversionVeto"
      - "barrel H/E"
      - "barrel MissingHits"

# same as above, but with electron-genA dR matching
barrelE_ID-EtaInSeed_matched: &barrelE_ID-EtaInSeed_matched
  <<: *barrelE_ID-EtaInSeed
  obj_cuts:
    <<: *obj_barrelE_ID-EtaInSeed
    electrons:
      - *e_barrelE_ID-EtaInSeed
      - "dR(e, A) < 0.5"

barrelE_ID-Inverse: &barrelE_ID-Inverse
  <<: *barrelE
  obj_cuts: &obj_barrelE_ID-Inverse
    <<: *obj_barrelE
    electrons: &e_barrelE_ID-Inverse
      - *e_barrelE
      - "barrel SigmaIEtaIEtaCut"
      - "barrel DPhiInCut"
      - "barrel DEtaInSeedCut"
      - "barrel Iso"
      - "barrel ConversionVeto"
      - "barrel H/E"
      - "barrel MissingHits"

# same as above, but with electron-genA dR matching
barrelE_ID-Inverse_matched: &barrelE_ID-Inverse_matched
  <<: *barrelE_ID-Inverse
  obj_cuts:
    <<: *obj_barrelE_ID-Inverse
    electrons:
      - *e_barrelE_ID-Inverse
      - "dR(e, A) < 0.5"

barrelE_ID-Iso: &barrelE_ID-Iso
  <<: *barrelE
  obj_cuts: &obj_barrelE_ID-Iso
    <<: *obj_barrelE
    electrons: &e_barrelE_ID-Iso
      - *e_barrelE
      - "barrel SigmaIEtaIEtaCut"
      - "barrel DPhiInCut"
      - "barrel DEtaInSeedCut"
      - "barrel InverseCut"
      - "barrel ConversionVeto"
      - "barrel H/E"
      - "barrel MissingHits"

# same as above, but with electron-genA dR matching
barrelE_ID-Iso_matched: &barrelE_ID-Iso_matched
  <<: *barrelE_ID-Iso
  obj_cuts:
    <<: *obj_barrelE_ID-Iso
    electrons:
      - *e_barrelE_ID-Iso
      - "dR(e, A) < 0.5"

barrelE_ID-ConversionVeto: &barrelE_ID-ConversionVeto
  <<: *barrelE
  obj_cuts: &obj_barrelE_ID-ConversionVeto
    <<: *obj_barrelE
    electrons: &e_barrelE_ID-ConversionVeto
      - *e_barrelE
      - "barrel SigmaIEtaIEtaCut"
      - "barrel DPhiInCut"
      - "barrel DEtaInSeedCut"
      - "barrel InverseCut"
      - "barrel Iso"
      - "barrel H/E"
      - "barrel MissingHits"

# same as above, but with electron-genA dR matching
barrelE_ID-ConversionVeto_matched: &barrelE_ID-ConversionVeto_matched
  <<: *barrelE_ID-ConversionVeto
  obj_cuts:
    <<: *obj_barrelE_ID-ConversionVeto
    electrons:
      - *e_barrelE_ID-ConversionVeto
      - "dR(e, A) < 0.5"

barrelE_ID-HE: &barrelE_ID-HE
  <<: *barrelE
  obj_cuts: &obj_barrelE_ID-HE
    <<: *obj_barrelE
    electrons: &e_barrelE_ID-HE
      - *e_barrelE
      - "barrel SigmaIEtaIEtaCut"
      - "barrel DPhiInCut"
      - "barrel DEtaInSeedCut"
      - "barrel InverseCut"
      - "barrel Iso"
      - "barrel ConversionVeto"
      - "barrel MissingHits"

# same as above, but with electron-genA dR matching
barrelE_ID-HE_matched: &barrelE_ID-HE_matched
  <<: *barrelE_ID-HE
  obj_cuts:
    <<: *obj_barrelE_ID-HE
    electrons:
      - *e_barrelE_ID-HE
      - "dR(e, A) < 0.5"

barrelE_ID-MissingHits: &barrelE_ID-MissingHits
  <<: *barrelE
  obj_cuts: &obj_barrelE_ID-MissingHits
    <<: *obj_barrelE
    electrons: &e_barrelE_ID-MissingHits
      - *e_barrelE
      - "barrel SigmaIEtaIEtaCut"
      - "barrel DPhiInCut"
      - "barrel DEtaInSeedCut"
      - "barrel InverseCut"
      - "barrel Iso"
      - "barrel ConversionVeto"
      - "barrel H/E"

# same as above, but with electron-genA dR matching
barrelE_ID-MissingHits_matched: &barrelE_ID-MissingHits_matched
  <<: *barrelE_ID-MissingHits
  obj_cuts:
    <<: *obj_barrelE_ID-MissingHits
    electrons:
      - *e_barrelE_ID-MissingHits
      - "dR(e, A) < 0.5"
